databases:
  - name: render_coda
    region: Oregon (US West)
    plan: free
    databaseName: render_coda
    user: render_user

services:
  - type: web
    name: render_coda
    env: python
    region: Oregon (US West)
    buildCommand: './build.sh'
    startCommand: 'python3 manage.py runserver'
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render_coda
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true
